app:
    resource: @AppBundle/Controller/
    type:     annotation

# Slide
slide_list:
    path:      /slides
    defaults:  { _controller: AppBundle:Slide:list }

slide_create:
    path:      /slide/create
    defaults:  { _controller: AppBundle:Slide:persist }

slide_edit:
    path:      /slide/edit/{id}
    defaults:  { _controller: AppBundle:Slide:persist }

slide_view:
    path:       /slide/view/{id}
    defaults:  { _controller: AppBundle:Slide:view }

slide_get_tile:
    path:       /slide/gettile/{id}/{level}/{x}/{y}
    defaults:  { _controller: AppBundle:Slide:getTile, level = 0, x = 0, y = 0 }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
